# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 22))
        self.menubar.setObjectName("menubar")
        self.menu123 = QtWidgets.QMenu(self.menubar)
        self.menu123.setObjectName("menu123")
        self.menu456 = QtWidgets.QMenu(self.menu123)
        self.menu456.setObjectName("menu456")
        self.menu444 = QtWidgets.QMenu(self.menubar)
        self.menu444.setObjectName("menu444")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionAbout = QtWidgets.QAction(MainWindow)
        self.actionAbout.setObjectName("actionAbout")
        self.action777 = QtWidgets.QAction(MainWindow)
        self.action777.setObjectName("action777")
        self.menu456.addAction(self.action777)
        self.menu123.addAction(self.menu456.menuAction())
        self.menubar.addAction(self.menu123.menuAction())
        self.menubar.addAction(self.menu444.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.menu123.setTitle(_translate("MainWindow", "123"))
        self.menu456.setTitle(_translate("MainWindow", "456"))
        self.menu444.setTitle(_translate("MainWindow", "444"))
        self.actionAbout.setText(_translate("MainWindow", "About"))
        self.action777.setText(_translate("MainWindow", "777"))
